"""empty message

Revision ID: a28c0e382860
Revises: f865da312edc
Create Date: 2022-08-26 20:13:44.274851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28c0e382860'
down_revision = 'f865da312edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('to_do', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('to_do', 'completed')
    # ### end Alembic commands ###
